name: starship-multichain-devnet
version: 1.10.0

chains:
  - id: solana
    name: solana
    numValidators: 1
    ports:
      rpc: 8899
      ws: 8900
      exposer: 8001
      faucet: 9900
    resources:
      cpu: "2.0"
      memory: "4Gi"

  - id: "1337"
    name: ethereum
    numValidators: 1
    ports:
      rest: 8545
      rpc: 8551
    resources:
      cpu: "0.5"
      memory: "500Mi"

  - id: osmosis-1
    name: osmosis
    numValidators: 1
    ports:
      rest: 1313
      rpc: 26653
      exposer: 38083
      faucet: 8001
    resources:
      cpu: "0.3"
      memory: "200Mi"

  - id: cosmoshub-4
    name: cosmoshub
    numValidators: 1
    faucet:
      enabled: false
    ports:
      rest: 1317
      rpc: 26657
      exposer: 38087
    resources:
      cpu: "0.3"
      memory: "200Mi"

relayers:
  - name: osmos-cosmos
    type: hermes
    replicas: 1
    chains:
      - osmosis-1
      - cosmoshub-4
    config:
      global:
        log_level: "error"
      rest:
        enabled: true
      telemetry:
        enabled: false
      event_source:
        mode: pull
    ports:
      rest: 3000
      exposer: 3002

explorer:
  enabled: true
  ports:
    rest: 8080
  resources:
    cpu: "0.5"
    memory: "500Mi"

registry:
  enabled: true
  ports:
    rest: 8081
    grpc: 9091